version: '3.8'
name: honest-config-server

services:
  config-server:
    image: ${IMAGE}
    container_name: honest-config-server
    environment:
      - CONFIG_SERVER_GIT_URL=${CONFIG_SERVER_GIT_URL}
      - CONFIG_SERVER_GIT_TOKEN=${CONFIG_SERVER_GIT_TOKEN}
    restart: always
    networks:
      - dc-net

networks:
  dc-net:
    external: true