spring:
  application:
    name: honest-config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_GIT_URL}
          searchPaths: '{application}'
          default-label: main
          clone-on-start: true
          strict-host-key-checking: false
          refresh-rate: 5
          password: ${CONFIG_SERVER_GIT_TOKEN}
          username: logotipiwe
      enabled: true


server:
  port: 8888